FROM registry.fedoraproject.org/fedora-minimal

LABEL maintainer="Sergiu Giurgiu <sgiurgiu11@gmail.com>"

ARG RDRPM=/tmp/reddit_desktop/packages/reddit_desktop-0.0.1-fedora.rpm

RUN curl -s http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm -o /tmp/rpmfusion-free-release-stable.noarch.rpm && \
    curl -s http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm -o /tmp/rpmfusion-nonfree-release-stable.noarch.rpm && \
    rpm -i /tmp/rpmfusion-free-release-stable.noarch.rpm && \
    rpm -i /tmp/rpmfusion-nonfree-release-stable.noarch.rpm && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-latest && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-latest

RUN  microdnf clean all && \
      microdnf -y install libglvnd-opengl openssl ibus-libs \
        freetype mpv-libs youtube-dl mesa-libGL mesa-libGLU mesa-dri-drivers && \
        microdnf -y upgrade && \
        microdnf clean all

RUN rpm -i ${RDRPM} &&  mkdir -p /root/.config/reddit_desktop

ENTRYPOINT ["/usr/bin/reddit_desktop"]
