ARG BASE_CONTAINER=localhost/reddit_desktop_fedora:runtime

FROM ${BASE_CONTAINER}

LABEL maintainer="Sergiu Giurgiu <sgiurgiu11@gmail.com>"

ARG RDRPM=/tmp/reddit_desktop/packages/reddit_desktop-0.0.1-fedora.rpm

RUN rpm -i ${RDRPM} &&  mkdir -p /root/.config/reddit_desktop

ENTRYPOINT ["/usr/bin/reddit_desktop"]
