FROM registry.fedoraproject.org/fedora-minimal

LABEL maintainer="Sergiu Giurgiu <sgiurgiu11@gmail.com>"


RUN curl -s http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm -o /tmp/rpmfusion-free-release-stable.noarch.rpm && \
    curl -s http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm -o /tmp/rpmfusion-nonfree-release-stable.noarch.rpm && \
    rpm -iv /tmp/rpmfusion-free-release-stable.noarch.rpm && \
    rpm -iv /tmp/rpmfusion-nonfree-release-stable.noarch.rpm && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-latest && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-latest

RUN  microdnf clean all && \
      microdnf -y install libglvnd-opengl firefox xdg-utils libSM libICE \
        mpv-libs youtube-dl mesa-libGL mesa-libGLU mesa-dri-drivers && \
#        microdnf -y upgrade && \
        microdnf clean all

CMD ["fedora"]

